sudo: required


services:
  - docker

before_install:
  - docker build . -t adobe/luamock

script:
  - ./run_unit_tests.sh

deploy:
  skip_cleanup: true
  provider: deploy
    deploy: bash deploy.sh snapshot
    except:
      branch: master
  provider: deploy
    deploy: bash deploy.sh production
    on:
      branch: master

